# -*- coding: utf-8 -*-
"""Copy of Animal Model Assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_h0owh3KdDISBr2J4226qKvllwzWixmg
"""

!pip install dlclibrary
from pathlib import Path
import os
import numpy as np
import kagglehub
import matplotlib.pyplot as plt
from tensorflow.keras.preprocessing.image import load_img, img_to_array
from keras import layers
from keras.models import Model
from keras.utils import to_categorical
from sklearn import metrics
from dlclibrary import download_huggingface_model
import zipfile
from PIL import Image


from google.colab import drive
drive.mount('/content/drive')

!git clone https://github.com/AdaptiveMotorControlLab/modelzoo-figures.git
# Create folder and download model
model_dir = Path("./superanimal_quadruped_model_pytorch")
model_dir.mkdir(exist_ok=True)
download_huggingface_model("superanimal_quadruped", model_dir)

data_folder = Path("modelzoo-figures")
quadruped_animal_path = "/content/drive/MyDrive/Quadruped Animal Images.zip"

# Extract quadruped animal file
extracted_folder = Path("quadruped_animal_extracted")
with zipfile.ZipFile(quadruped_animal_path, 'r') as zip_ref:
    zip_ref.extractall(extracted_folder)

# Load quadruped images from the extracted folder
def load_quadruped_images_from_folder(folder_path):
    images = []
    for root, dirs, files in os.walk(folder_path):
        for filename in files:
            if filename.endswith(".jpg") or filename.endswith(".png"):
                img_path = os.path.join(root, filename)
                img = Image.open(img_path)
                if img.mode != 'RGB':
                    img = img.convert('RGB')
                img = img.resize((224, 224))
                img = np.array(img)
                images.append(img)
    return np.array(images)

# Load images from extracted ZIP file
quadruped_images = load_quadruped_images_from_folder(extracted_folder)
print(f"Loaded {len(quadruped_images)} quadruped images from the ZIP file.")

zip_file_path = "/content/drive/MyDrive/archive.zip"
with zipfile.ZipFile(zip_file_path, 'r') as zip_ref:
    zip_ref.extractall("extracted_images")

# Load animal face images
def load_animal_face_images(data_folder, folders_to_use=["cat", "dog"], num_images_per_folder=10):
    images = []
    labels = []
    for folder_name in folders_to_use:
        folder_path = data_folder / folder_name
        image_count = 0
        for filename in os.listdir(folder_path):
            if filename.endswith(".jpg") or filename.endswith(".png"):
                img = load_img(folder_path / filename, target_size=(224, 224))
                img = img_to_array(img)
                images.append(img)
                labels.append(0 if folder_name == "cat" else 1)
                image_count += 1
                if image_count >= num_images_per_folder:
                    break
    return np.array(images), np.array(labels)

# Limit the amount of quadruped images
def load_quadruped_images_with_limit(data_folder, folders_to_use=["cats", "dogs"], num_images_per_folder=5):
    images = []
    labels = []
    for folder_name in folders_to_use:
        folder_path = data_folder / folder_name
        image_count = 0
        for filename in os.listdir(folder_path):
            if filename.endswith(".jpg") or filename.endswith(".png"):
                img = load_img(folder_path / filename, target_size=(224, 224))
                img = img_to_array(img)
                images.append(img)
                labels.append(0 if folder_name == "cats" else 1)
                image_count += 1
                if image_count >= num_images_per_folder:
                    break
    return np.array(images), np.array(labels)

# Limit is 5 images for cat and dog
limited_animal_face_images, limited_labels = load_quadruped_images_with_limit(
    Path("extracted_images"),
    folders_to_use=["cat", "dog"],
    num_images_per_folder=5
)

# Data normalization
limited_animal_face_images = limited_animal_face_images.astype('float32') / 255.0

# Apply limit function to quadruped images
quadruped_images = limited_animal_face_images

animal_face_images, labels = load_animal_face_images(Path("extracted_images"), num_images_per_folder=5)
print(f"Loaded {len(animal_face_images)} animal face images.")

# Normalize face images
animal_face_images = animal_face_images.astype('float32') / 255.0

# Seperate cat and dog images for visualization
cat_images = animal_face_images[labels == 0][:5]
dog_images = animal_face_images[labels == 1][:5]
cat_labels = labels[labels == 0][:5]
dog_labels = labels[labels == 1][:5]

combined_images = np.concatenate((cat_images, dog_images), axis=0)
combined_labels = np.concatenate((cat_labels, dog_labels), axis=0)

def show_images_with_labels(images, labels, title):
    """Displays images in a grid with their labels."""
    plt.figure(figsize=(10, 10))
    for i in range(len(images)):
        plt.subplot(2, 5, i + 1)
        img = images[i] * 255.0 if images[i].max() <= 1.0 else images[i]
        plt.imshow(img.astype("uint8"))
        plt.title("Cat" if labels[i] == 0 else "Dog")
        plt.axis("off")
    plt.suptitle(title)
    plt.tight_layout()
    plt.show()

show_images_with_labels(combined_images, combined_labels, "Sample Cat and Dog Images")

# Load images with minimum samples
min_samples = min(len(quadruped_images), len(animal_face_images))
quadruped_images = quadruped_images[:min_samples]
animal_face_images = animal_face_images[:min_samples]

# Create labels (Cat = 0, Dog = 1)
y_train = np.random.randint(0, 2, min_samples)
y_test = np.random.randint(0, 2, min_samples)

y_train = to_categorical(y_train, 2)
y_test = to_categorical(y_test, 2)

# classify quadruped images based on prediction labels
pose_input = layers.Input(shape=(224, 224, 3))
x1 = layers.Conv2D(32, (3, 3), activation='relu')(pose_input)
x1 = layers.MaxPooling2D((2, 2))(x1)
x1 = layers.Flatten()(x1)

# Define the model for prediction
x = layers.Dense(200, activation='relu')(x1)
x = layers.Dropout(0.5)(x)
x = layers.Dense(200, activation='relu')(x)
x = layers.Dense(2, activation='softmax')(x)

# Create the model
model = Model(inputs=pose_input, outputs=x)

# Compile the model
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
model.summary()

# Train the model
history = model.fit(
    quadruped_images,
    y_train,
    batch_size=32,
    epochs=15,
    validation_data=(quadruped_images, y_test)
)

# Evaluate the model on the test set
test_loss, test_acc = model.evaluate(quadruped_images, y_test)
print(f"Test accuracy: {test_acc}")
print(f"Test loss: {test_loss}")

# Plot training history
plt.figure(figsize=(12, 4))
plt.subplot(1, 2, 1)
plt.plot(history.history['loss'], label='Training Loss')
plt.plot(history.history['val_loss'], label='Validation Loss')
plt.title('Model Loss')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.legend()

plt.subplot(1, 2, 2)
plt.plot(history.history['accuracy'], label='Training Accuracy')
plt.plot(history.history['val_accuracy'], label='Validation Accuracy')
plt.title('Model Accuracy')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.legend()
plt.tight_layout()

predictions = model.predict(quadruped_images)

predicted_classes = np.argmax(predictions, axis=1)

# Display the predicted class labels
for i in range(len(predicted_classes)):
    print(f"Image {i}: Predicted Class: {'Cat' if predicted_classes[i] == 0 else 'Dog'}")

# Visualize some predictions
def show_predictions_with_labels(images, predicted_labels, true_labels):
    """Displays images in a grid with their true and predicted labels."""
    plt.figure(figsize=(10, 10))
    for i in range(len(images)):
        plt.subplot(2, 5, i + 1)
        img = images[i] * 255.0 if images[i].max() <= 1.0 else images[i]
        plt.imshow(img.astype("uint8"))
        plt.title(f"True: {'Cat' if true_labels[i] == 0 else 'Dog'}\nPred: {'Cat' if predicted_labels[i] == 0 else 'Dog'}")
        plt.axis("off")
    plt.tight_layout()
    plt.show()
# Display predictions for the test set
show_predictions_with_labels(quadruped_images, predicted_classes, np.argmax(y_test, axis=1))

available_models = dlc.get_available_models('superanimal_quadruped')
print(available_models)  # Debugging step to see what it returns

from dlclibrary.dlcmodelzoo.modelzoo_download import test_

from huggingface_hub import hf_hub_download, login

# Log in to your Hugging Face account
login() # you will be prompted to enter your token

# ... (rest of your code)

# Download the model with token authentication
model_path = hf_hub_download(
    repo_id="DeepLabCut/superanimal_quadruped",
    filename="resnet_50.pth",
    use_auth_token=True  # This ensures your token is used for the request
)

import dlclibrary as dlc

test_model = dlc.get_available_models('superanimal_quadruped')

!pip install transformers torch